name: qubic_wallet
description: A Wallet for the Qubic Network created by Qubic-Hub.com
publish_to: "none"
version: 0.8.5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  from_css_color: ^2.0.0
  google_fonts: ^5.1.0
  intl:
  json_path: ^0.6.2
  page_transition: ^2.0.9
  shared_preferences: ^2.2.0
  timeago: ^3.5.0
  url_launcher: ^6.1.12
  mobx: ^2.2.0
  flutter_mobx:
  flutter_secure_storage: ^8.0.0
  go_router: ^10.1.0
  get_it: ^7.6.0
  form_builder_validators: ^9.0.0
  flex_color_scheme:
  dargon2_flutter: ^3.3.0
  flutter_form_builder: ^9.1.0
  persistent_bottom_nav_bar: ^5.0.2
  dotted_border: ^2.0.0+3
  flutter_inappwebview: ^6.0.0-beta.24+1
  skeleton_text: ^3.0.1
  qr_flutter: ^4.1.0
  share_plus: ^7.1.0
  mobile_scanner: ^3.4.1
  flutter_multi_formatter: ^2.11.11
  pagination_flutter: ^0.0.8
  sticky_headers: "^0.3.0"
  equatable: ^2.0.5
  settings_ui: ^2.0.2
  package_info_plus: ^4.2.0
  local_auth: ^2.1.7
  http: ^1.1.0
  universal_platform: ^1.0.0+1
  path_provider: ^2.1.1
  window_manager: ^0.3.7
  dio: ^5.3.3
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  mobx_codegen: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter_native_splash:
  color: "#333333"
  image: "assets/images/logo_blue.png"
  android_12:
    color: "#333333"
    image: "assets/images/qubic_android.png"

flutter_launcher_icons:
  image_path_android: "assets/launcher-icons/icon-1024x1024.png"
  image_path_ios: "assets/launcher-icons/icon-1024x1024.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#000000"
  windows:
    generate: true
    image_path: "assets/launcher-icons/icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/launcher-icons/icon-1024x1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/launcher-icons/
    - assets/qubic_js/
